name: myenv
channels:
  - conda-forge
dependencies:
  - flask
  - html5lib
  - librosa
  - numpy
  - numpy-base
  - pandas
  - pickleshare
  - pysoundfile
  - scikit-learn=0.22.2
  - scipy
  - unicodecsv